# Generated by Django 3.1.7 on 2021-02-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210227_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='video_url',
            field=models.CharField(max_length=255),
        ),
    ]
