# Generated by Django 3.1.7 on 2021-02-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_auto_20210220_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
